language: perl
perl:
    - "5.20"
    - "5.22"
    - "5.24"
    - "dev"
    - "blead"
matrix:
    allow_failures:
        - perl: blead
sudo: false
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - cpan-install Code::TidyAll::Plugin::PerlCritic Perl::Critic 
    - build-dist
    - cd $BUILD_DIR
install:
    - cpan-install --deps
notifications:
    email:
        on_success: always
        on_failure: always