markdown: kramdown

defaults:
  -
   scope:
     path: ""
     type: "pages"
   values:
     layout: "default"
     author: "Heinz Knutzen"

baseurl: "/Netspoc" # the subpath of your site, e.g. /blog
url: "http://hknutzen.github.io" # the base hostname & protocol for your site
github_username: hknutzen
